import { Inter,Roboto } from "next/font/google";
import NavBar from "@/components/navbar/navbar";
import Providers from "@/Redux/provider";

const roboto = Roboto({ subsets: ["latin"] , weight:"500"});


export const metadata = {
  title: "teerex store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className} style={{zIndex:-1,position:"relative"}}>
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
